version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumns:
      - /usr/app/node_modules
      - .:/usr/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumns:
      - /usr/app/node_modules
      - .:/usr/app
    command: ['npm', 'run', 'test']
